import Navbar from '@/components/Navbar'
import './globals.css'
import Provider from '@/components/Provider'

export const metadata = {
  title: 'Thought Space',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
   <Provider>

   <body>

<Navbar />
<section className='cursor-pointer container mx-auto'>

 {children}
 </section>
</body>
   </Provider>
    </html>
  )
}
